version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/action
    overwrite: yes

permissions:
  - object: /home/ec2-user/action
    owner: ec2-user


hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user
