
name: Build and Deploy

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./fitback-security
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.working-directory }}
        
      - name: Build with Gradle
        run: ./gradlew 
        shell: bash
        working-directory: ${{ env.working-directory }}
          
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash
        
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          

      - name: Upload to AWS S3
        run: >
          aws deploy push
          --application-name ${{ secrets.CODE_DEPLOY }}
          --ignore-hidden-files
          --s3-location s3://${{ secrets.S3BUCKET }}/$GITHUB_SHA.zip
          --source .
          
      - name: Code Deploy
        run: >
          aws deploy create-deployment --application-name ${{ secrets.CODE_DEPLOY }}
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name ${{ secrets.CODE_DEPLOY_GROUP }}
          --file-exists-behavior OVERWRITE
          --s3-location bucket=${{ secrets.S3BUCKET }},bundleType=zip,key=$GITHUB_SHA.zip
