#fitback-deploy

name: Build and Deploy

on:
  push:
    branches: [ "master" ]
    
permissions:
  contents: read
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Add permission
        run: chmod +x gradlew
        shell: bash
        working-directory: ${{ env.working-directory }}
        
      - name: Build with Gradle
        run: ./gradlew 
        shell: bash
        working-directory: ${{ env.working-directory }}
          
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash
        working-directory: ${{ env.working-directory }}
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Upload Artifact to s3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{ env.S3BUCKET }}/${{ env.PROJECT_NAME }}/$GITHUB_SHA.zip
        working-directory: ${{ env.working-directory }}
